### ISSUE TITLE
when hosting with relay host it requires to download "Spring *"

### ISSUE THREAD

**Issue by TurBoss** [spring/relayhost#3]
![imagen](https://user-images.githubusercontent.com/184088/52016427-cfdcac80-24e4-11e9-8d8c-f59798f23be1.png)

**Comment by TurBoss** [comment]
https://github.com/spring/uberserver/issues/301

**Comment by abma** [comment]
very likely was introduced by removing the default engine version in uberserver

**Comment by abma** [comment]
ugh, this is more complicate than i thought:

'*' very likely is sent from springlobby, so:

1. springlobby needs to send the version it sets when hosting with relayhost
2. relayhost needs to support multiple versions / autodownload missing versions

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/blob/master/src/tasserver.cpp#L1268

**Comment by abma** [comment]
springlobby change is done, now the relayhost needs to be updated :-|

**Comment by abma** [comment]
IMHO relayhost should self-check if he has a botflag: if not: deny hosting

**Comment by abma** [comment]
https://github.com/spring/relayhost/commit/cfae52f55b6d8b00fe667247aaebaa180207f738

**Comment by TurBoss** [comment]
Thanks
